version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - app-network

  adventour-backend:
    depends_on:
      - redis
    container_name: adventour-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - config.env
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '${PORT:-2000}:${PORT:-2000}'
    volumes:
      - /app/node_modules # prevent node_modules to be overwritten create anonymous volume
      - .:/app
    # bind the current directory to /app in the container so that file changes in dev mode are reflected in the container

networks:
  app-network:
    driver: bridge
