version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: reddis
    ports:
      - 6379:6379

  adventour-backend:
    depends_on:
      - redis
    container_name: adventour_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./config.env
    ports:
      - '${PORT:-2000}:${PORT:-2000}'
    volumes:
      - /app/node_modules # prevent node_modules to be overwritten using anonymous volume
